-- 코드를 입력하세요
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS
USING (ANIMAL_ID)
WHERE SEX_UPON_INTAKE NOT IN ("Neutered Male","Spayed Female") AND SEX_UPON_OUTCOME IN ("Neutered Male","Spayed Female")
ORDER BY INS.ANIMAL_ID