-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS D JOIN(
    SELECT *
    FROM SKILLCODES
    WHERE CATEGORY = "Front End"
) C
ON (D.SKILL_CODE & C.CODE) = C.CODE
ORDER BY ID