-- 코드를 작성해주세요
SELECT YEAR, YEAR_MAXSIZE - SIZE_OF_COLONY YEAR_DEV, ID
FROM ECOLI_DATA ED JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) YEAR_MAXSIZE
    FROM ECOLI_DATA
    GROUP BY 1) YM ON YEAR(ED.DIFFERENTIATION_DATE)=YM.YEAR
ORDER BY YEAR, YEAR_DEV